name: repo_viewer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.5.0
  material_design_icons_flutter: ^5.0.6595
  oauth2: ^2.0.0
  path: any
  path_provider: ^2.0.11
  sembast: ^3.2.0+1
  shimmer: ^2.0.0
  webview_flutter: ^3.0.4
  material_floating_search_bar: ^0.3.7
  
dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

dependency_overrides:
  flutter_riverpod:
  riverpod:

flutter:
  uses-material-design: true
